# Generated by Django 6.0.5 on 2026-05-11 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_payment_created_at_payment_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['status'], name='services_se_status_d2293e_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['created_at'], name='services_se_created_c72088_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['created_by'], name='services_se_created_84b0bc_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['status', 'created_at', 'created_by'], name='services_se_status_39945b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['created_by'], name='services_ve_created_375e26_idx'),
        ),
    ]
